<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="MBadillo-EDP-100-327.local" failures="1" tests="5" name="Personal Loan" time="0.062" errors="0" timestamp="2023-03-02T09:20:16 PST">
  <testcase classname="TestPackage.day1" name="Demo" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestPackage.day1.Demo(day1.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="TestPackage.day2" name="ploan" time="0.001"/>
  <testcase classname="TestPackage.day4" name="LoginAPIHomeLoan" time="0.002"/>
  <testcase classname="TestPackage.day4" name="MobileLoginHomeLoan" time="0.004"/>
  <testcase classname="TestPackage.day4" name="WebloginHomeLoan" time="0.003"/>
  <testcase classname="TestPackage.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
